name: MarketObserver
host: 127.0.0.1
port: 8001
log_level: "INFO"
grpc_host: "localhost"
grpc_port: 50051

storage:
  db_type: sqlite
  db_path: stocks.db
  db_connection_string: postgresql://user:password@localhost/dbname

network:
  enabled: false
  timeout: 10
  retries: 3
  concurrent_requests: 25
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
  proxies: []

# windows_aggregation parsed with ParseDuration: 
# A duration string is a possibly signed sequence of decimal numbers, 
# each with optional fraction and a unit suffix, such as :
# "300ms", "-1.5h" or "2h45m". 
# Valid time units are "ns", "us" (or "Âµs"), "ms", "s", "m", "h".
windows_aggregation:
  - 5m
  - 10m
  - 15m
  - 30m
  - 1h
  - 2h
  - 4h
  - 6h

data_source:
  data_retention_days: 7
  update_interval_seconds: 300
  sources:
    - name: "yahoo"
      symbols:
      # for postgres database we can load symbol from a table
      # example: "schema.table.field"
        - AAPL
        - MSFT
        - GOOGL
        - AMZN
        - NVDA
        - TSLA
        - META
        - BRK-B
        - UNH
        - JNJ
        - JPM
        - XOM
        - V
        - PG
        - MA
        - HD
        - CVX
        - ABBV
        - MRK
        - PEP
        - LULU
        - RCL
        - AVGO
        - COST
        - CSCO
        - MCD
        - WMT
        - TMO
        - BAC
        - CRM
        - PFE
        - KO
        - LIN
        - WFC
        - AMD
        - DIS
        - DHR
        - TXN
        - PM
        - MS
        - NKE
        - NEE
        - UPS
        - BMY
        - RTX
        - AMGN
        - HON
        - T
        - BA
        - IBM
        - UNP
        - LOW
        - ELV
        - SPGI
        - CVS
        - CAT
        - GS
        - DE
        - LMT
        - INTU
        - QCOM
        - PLD
        - SCHW
        - BLK
        - ORCL
        - AMT
        - GILD
        - SBUX
        - C
        - ISRG
        - AXP
        - MDT
        - NOW
        - ZTS
        - SYK
        - EL
        - TJX
        - ADP
        - C
        - MO
        - CB
        - MMC
        - GE
        - ADI
        - TMUS
        - VRTX
        - EOG
        - SO
        - REGN
        - CI
        - BDX
        - PYPL
        - FISV
        - BSX
        - AON
        - ITW
        - CL
        - APD
        - EW
        - PANW
        - CHTR
        - ETN